#include "pico/stdlib.h"
#include "hardware/spi.h"
#include "st7735.h"
#include "sd_card.h"
#include "bmp.h"
#include "usb_msc.h"
#include "ff.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

// ── User configuration ────────────────────────────────────────────────────────
#define CHARACTER    "sayuri"  // which character to display
#define FRAME_MS     180          // ms per animation frame
#define CHECK_EVERY  30           // re-check SD fullness every N frames
#define MAX_FRAMES   16           // max frames per state held in RAM

// ── Enums ─────────────────────────────────────────────────────────────────────
typedef enum { TIER_SMALL=0, TIER_MEDIUM, TIER_LARGE, TIER_COUNT } Tier;
typedef enum { STATE_IDLE=0, STATE_TRANSFER, STATE_CONNECT, STATE_ENDTRANSFER, STATE_COUNT } AnimState;

static const char *tier_name[TIER_COUNT]   = { "SMALL", "MEDIUM", "LARGE" };
static const char *state_name[STATE_COUNT] = { "IDLE", "TRANSFER", "CONNECT", "ENDTRANSFER" };

// ── Sprites (generated by convert_sprites.sh) ─────────────────────────────────
#ifdef __has_include
#  if __has_include("sprites.h")
#    include "sprites.h"
#  else
     typedef struct { const uint8_t *data; uint32_t len; int tier; int state; const char *character; } SpriteEntry;
     static const SpriteEntry sprite_table[] = {};
     static const int sprite_table_len = 0;
#  endif
#else
#  include "sprites.h"
#endif

// ── Frame cache ───────────────────────────────────────────────────────────────
typedef struct { uint8_t *pixels; int w, h; } Frame;
static Frame _frames[MAX_FRAMES];
static int   _frame_count  = 0;
static Tier  _current_tier = (Tier)-1;

static void free_frames(void) {
    for (int i = 0; i < _frame_count; i++) {
        free(_frames[i].pixels);
        _frames[i].pixels = NULL;
    }
    _frame_count = 0;
}

// ── SD fullness ───────────────────────────────────────────────────────────────
static float sd_used_fraction(void) {
    FATFS *fsp; DWORD free_clust;
    mutex_enter_blocking(&sd_mutex);
    FRESULT r = f_getfree("", &free_clust, &fsp);
    mutex_exit(&sd_mutex);
    if (r != FR_OK) return 0.0f;
    uint32_t total = (fsp->n_fatent - 2) * fsp->csize;
    uint32_t used  = total - free_clust * fsp->csize;
    return total ? (float)used / (float)total : 0.0f;
}

static Tier tier_for(float f) {
    if (f < 0.33f) return TIER_SMALL;
    if (f < 0.66f) return TIER_MEDIUM;
    return TIER_LARGE;
}

// ── Load frames (with tier+state fallback) ────────────────────────────────────
static void load_frames(Tier t, AnimState s) {
    free_frames();
    _current_tier = t;

    // Fallback order: requested state → IDLE
    AnimState state_order[2] = { s, STATE_IDLE };
    int n_states = (s == STATE_IDLE) ? 1 : 2;

    // Fallback order: requested tier → nearest smaller → nearest larger
    Tier tier_order[TIER_COUNT];
    int  n_tiers = 0;
    tier_order[n_tiers++] = t;
    for (int d = 1; d < TIER_COUNT; d++) {
        if ((int)t - d >= 0)         tier_order[n_tiers++] = (Tier)(t - d);
        if ((int)t + d < TIER_COUNT) tier_order[n_tiers++] = (Tier)(t + d);
    }

    for (int si = 0; si < n_states && _frame_count == 0; si++) {
        for (int ti = 0; ti < n_tiers && _frame_count == 0; ti++) {
            for (int i = 0; i < sprite_table_len && _frame_count < MAX_FRAMES; i++) {
                const SpriteEntry *e = &sprite_table[i];
                if (e->tier  != (int)tier_order[ti])  continue;
                if (e->state != (int)state_order[si]) continue;
                if (strcmp(e->character, CHARACTER)   != 0) continue;
                int w, h;
                uint8_t *px = bmp_load_mem(e->data, e->len, &w, &h);
                if (px) {
                    _frames[_frame_count].pixels = px;
                    _frames[_frame_count].w = w;
                    _frames[_frame_count].h = h;
                    _frame_count++;
                }
            }
            if (_frame_count > 0) {
                printf("%s %s_%s: %d frame(s)%s\n",
                    CHARACTER, tier_name[tier_order[ti]], state_name[state_order[si]],
                    _frame_count,
                    (tier_order[ti] != t || state_order[si] != s) ? " [fallback]" : "");
            }
        }
    }

    if (_frame_count == 0)
        printf("%s: no sprites found, using placeholder\n", CHARACTER);
}

// ── Placeholder ───────────────────────────────────────────────────────────────
static uint8_t _placeholder_buf[16*16*2];

static void make_placeholder(Tier t) {
    uint16_t cols[TIER_COUNT] = {
        SWAP16(RGB565(  0, 210, 220)),
        SWAP16(RGB565(255, 140,   0)),
        SWAP16(RGB565(220,  30, 180)),
    };
    uint16_t c = cols[t];
    for (int i = 0; i < 16*16*2; i += 2) {
        _placeholder_buf[i]   = (c >> 8) & 0xFF;
        _placeholder_buf[i+1] =  c & 0xFF;
    }
}

// ── USB transfer tracking ─────────────────────────────────────────────────────
#define MSC_IDLE_TIMEOUT_MS 1500
static volatile bool     _msc_write_active  = false;
static volatile uint32_t _msc_last_write_ms = 0;

void notify_msc_write(void) {
    _msc_write_active  = true;
    _msc_last_write_ms = to_ms_since_boot(get_absolute_time());
}

// ── Main ──────────────────────────────────────────────────────────────────────
static FATFS _fs;   // file scope so remount handler can reuse it

int main(void) {
    stdio_init_all();
    sleep_ms(200);
    printf("Tamagotchi starting — character: %s\n", CHARACTER);

    tft_init();
    tft_fill(COL_BLACK);

    bool sd_ok = sd_init();
    if (sd_ok) {
        FRESULT r = f_mount(&_fs, "", 1);
        sd_ok = (r == FR_OK);
        if (!sd_ok) printf("FatFs mount failed: %d\n", r);
        else        printf("FatFs mounted\n");
    } else {
        printf("SD init failed\n");
        tft_fill(SWAP16(RGB565(180, 0, 0)));
        sleep_ms(300);
        tft_fill(COL_BLACK);
    }

    usb_msc_init();

    // ── State machine ──────────────────────────────────────────────────────────
    AnimState anim_state   = STATE_CONNECT;
    Tier      tier         = TIER_SMALL;
    int       frame_idx    = 0;
    int       tick         = 0;
    bool      first_draw   = true;
    bool      one_shot_done = false;
    bool      was_transferring = false;

    load_frames(tier, anim_state);

    while (true) {
        usb_msc_task();
        uint32_t now_ms = to_ms_since_boot(get_absolute_time());

        // ── Transfer detection ─────────────────────────────────────────────────
        bool is_transferring = _msc_write_active &&
            (now_ms - _msc_last_write_ms) < MSC_IDLE_TIMEOUT_MS;

        if (!was_transferring && is_transferring &&
             anim_state != STATE_TRANSFER) {
            anim_state = STATE_TRANSFER;
            frame_idx = 0; first_draw = true; one_shot_done = false;
            load_frames(tier, STATE_TRANSFER);
        } else if (was_transferring && !is_transferring) {
            _msc_write_active = false;
            // Remount FatFs so its FAT cache reflects what the host just wrote
            if (sd_ok) {
                mutex_enter_blocking(&sd_mutex);
                f_unmount("");
                sd_ok = (f_mount(&_fs, "", 1) == FR_OK);
                mutex_exit(&sd_mutex);
                printf("FatFs remounted after transfer: %s\n", sd_ok ? "ok" : "fail");
            }
            anim_state = STATE_ENDTRANSFER;
            frame_idx = 0; first_draw = true; one_shot_done = false;
            load_frames(tier, STATE_ENDTRANSFER);
        }
        was_transferring = is_transferring;

        // ── Tier check (only while idle) ───────────────────────────────────────
        if (anim_state == STATE_IDLE && tick % CHECK_EVERY == 0) {
            Tier new_tier = tier_for(sd_ok ? sd_used_fraction() : 0.0f);
            if (new_tier != tier) {
                tier = new_tier;
                frame_idx = 0; first_draw = true;
                load_frames(tier, STATE_IDLE);
            }
        }

        // ── Play-once: CONNECT / ENDTRANSFER → IDLE on last frame ─────────────
        int  n_frames    = _frame_count > 0 ? _frame_count : 1;
        bool is_one_shot = (anim_state == STATE_CONNECT ||
                            anim_state == STATE_ENDTRANSFER);
        if (is_one_shot && !one_shot_done && frame_idx >= n_frames - 1 && tick > 0) {
            one_shot_done = true;
            anim_state    = STATE_IDLE;
            frame_idx     = 0; first_draw = true;
            load_frames(tier, STATE_IDLE);
        }

        // ── Draw ───────────────────────────────────────────────────────────────
        if (_frame_count > 0) {
            Frame *f = &_frames[frame_idx % _frame_count];
            tft_blit_scaled(f->pixels, f->w, f->h, first_draw);
        } else {
            make_placeholder(tier);
            tft_blit_scaled(_placeholder_buf, 16, 16, first_draw);
        }
        first_draw = false;
        frame_idx  = (frame_idx + 1) % n_frames;
        tick       = (tick + 1) % (CHECK_EVERY * 100000);

        // ── Frame delay ────────────────────────────────────────────────────────
        absolute_time_t deadline = make_timeout_time_ms(FRAME_MS);
        while (!time_reached(deadline)) {
            usb_msc_task();
            sleep_us(100);
        }
    }
    return 0;
}